SELECT * FROM EMP;

--TO FIND THE AVG
SELECT AVG(SAL) AVG_SALARY FROM EMP;

--TO FIND THE MAX 

SELECT MAX(SAL) MAX_SALARY FROM EMP;

--TO FIND THE MIN SALARY

SELECT MIN(SAL) MINMUM_SALARY FROM EMP;

--TO FIND THE COUNT OF THE TABLE

SELECT COUNT(SAL) COUNT_SAL FROM EMP;


