
SELECT * FROM USER_TABLES;
-- TO CREATE A STUDENT TABLE
CREATE TABLE Student(
   SID NUMBER,
   SNAME VARCHAR2(50),
   BRANCH VARCHAR2(50),
   PER NUMBER
);


INSERT INTO Student(SID,SNAME,BRANCH,PER)
VALUES(1,'A','ECE',60);

INSERT INTO Student (SID, SNAME, BRANCH, PER) VALUES (2, 'B', 'CSE', 75);
INSERT INTO Student (SID, SNAME, BRANCH, PER) VALUES (3, 'C', 'ME', 50);
INSERT INTO Student (SID, SNAME, BRANCH, PER) VALUES (4, 'D', 'ECE', 80);
INSERT INTO Student (SID, SNAME, BRANCH, PER) VALUES (5, 'E', 'CSE', 75);
INSERT INTO Student (SID, SNAME, BRANCH, PER) VALUES (6, 'F', 'CIVIL', 95);

--1.WAQTD student id and student names for all the students


SELECT s.SID STUDENT_ID,S.sname STUDENT_NAME FROM student s;


--2.WAQTD name and branch of all the students

SELECT S.sname STUDENT_NAME,S.branch STUDENT_BRANCH FROM STUDENT S ;


--3.WAQTD NAME , BRANCH AND PERCENTAGE FOR ALL THE STUDENTS 


SELECT sname ,S.branch ,S.per  FROM STUDENT S;

--4 WAQTD details of all the students from students table .


SELECT * FROM STUDENT;

--5 WAQTD sname , sid , per , branch of all the students .

SELECT S.SNAME,S.SID,S.PER FROM STUDENT S;


-- TO CREATE EMP TABLE 

CREATE TABLE EMP (
    EMPNO    NUMBER(4)     PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    HIREDATE DATE,
    MGR      NUMBER(4),
    SAL      NUMBER(7,2),
    COMM     NUMBER(7,2),
    DEPTNO   NUMBER(2)
);

INSERT INTO EMP VALUES (7369, 'SMITH',  'CLERK',    TO_DATE('17-DEC-80', 'DD-MON-YY'), 7902,  800, NULL, 20);
INSERT INTO EMP VALUES (7499, 'ALLEN',  'SALESMAN', TO_DATE('20-FEB-81', 'DD-MON-YY'), 7698, 1600,  300, 30);
INSERT INTO EMP VALUES (7521, 'WARD',   'SALESMAN', TO_DATE('22-FEB-81', 'DD-MON-YY'), 7698, 1250,  500, 30);
INSERT INTO EMP VALUES (7566, 'JONES',  'MANAGER',  TO_DATE('02-APR-81', 'DD-MON-YY'), 7839, 2975, NULL, 20);
INSERT INTO EMP VALUES (7654, 'MARTIN', 'SALESMAN', TO_DATE('28-SEP-81', 'DD-MON-YY'), 7698, 1250, 1400, 30);
INSERT INTO EMP VALUES (7698, 'BLAKE',  'MANAGER',  TO_DATE('01-MAY-81', 'DD-MON-YY'), 7839, 2850, NULL, 30);
INSERT INTO EMP VALUES (7782, 'CLARK',  'MANAGER',  TO_DATE('09-JUN-81', 'DD-MON-YY'), 7839, 2450, NULL, 10);
INSERT INTO EMP VALUES (7788, 'SCOTT',  'ANALYST',  TO_DATE('19-APR-87', 'DD-MON-YY'), 7566, 3000, NULL, 20);
INSERT INTO EMP VALUES (7839, 'KING',   'PRESIDENT',TO_DATE('17-NOV-81', 'DD-MON-YY'), NULL, 5000, NULL, 10);
INSERT INTO EMP VALUES (7844, 'TURNER','SALESMAN', TO_DATE('08-SEP-81', 'DD-MON-YY'), 7698, 1500,    0, 30);
INSERT INTO EMP VALUES (7876, 'ADAMS',  'CLERK',    TO_DATE('23-MAY-87', 'DD-MON-YY'), 7788, 1100, NULL, 20);
INSERT INTO EMP VALUES (7900, 'JAMES',  'CLERK',    TO_DATE('03-DEC-81', 'DD-MON-YY'), 7698,  950, NULL, 30);
INSERT INTO EMP VALUES (7902, 'FORD',   'ANALYST',  TO_DATE('03-DEC-81', 'DD-MON-YY'), 7566, 3000, NULL, 20);
INSERT INTO EMP VALUES (7934, 'MILLER', 'CLERK',    TO_DATE('23-JAN-82', 'DD-MON-YY'), 7782, 1300, NULL, 10);

SELECT * FROM EMP;


-- WAQTD name salary and commission given to all the employees .

SELECT e.sal salary,e.comm comission FROM EMP e;

--WAQTD name of the employee along with their date of joining 

SELECT e.ename Emploeename,e.HIREDATE dateofJoing FROM EMP e;


--TO create a Dep_table

CREATE TABLE DEPT (
    DEPTNO NUMBER(2)     PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH',   'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

commit;

-- WAQTD dname and location for all the depts .

SELECT d.dname,d.loc FROM DEPT d;


--ASSIGNMENT-1

-- 1.WRITE A QUERY TO DISPLAY ALL THE DETAILS FROM THE EMP
SELECT * FROM EMP;

-- 2..WAQTD NAMES OF ALL THE EMPLOYEES
SELECT e.ename FROM EMP e ;

-- 3.WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES

SELECT e.ename,e.sal FROM EMP e;

-- 4.WAQTD NAME AND COMMISSION GIVEN TO ALL THE EMPLOYEES.

SELECT e.ename,e.comm from emp e;

-- 5.WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL THE EMPLOYEES  IN EMP TABLE

SELECT e.empno,e.deptno FROM EMP e ;
-- 6..WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES

SELECT e.ename,e.hiredate FROM EMP e;

-- 7..WAQTD NAME AND DESIGNATION OF ALL THE EMPLPOYEES

SELECT e.ename NAME,e.job DESIGNATION FROM EMP e;

-- 8..WAQTD NAME , JOB AND SALARY GIVEN ALL THE EMPLOYEES

SELECT e.ename Name,e.job, e.sal salary FROM EMP e ;

-- 9. WAQTD DNAMES PRESENT IN DEPARTMENT TABLE.

SELECT d.dname DepartMentName FROM DEPT d;

-- 10.WAQTD DNAME AND LOCATION PRESENT IN DEPT TABLE.

SELECT d.dname DepName,d.loc DepLocation FROM DEPT d;

