--1.WRITE A QUERY TO DISPLAY ALL THE DETAILS FROM THE EMPLOYEE TABLE

SELECT * FROM EMPLOYEES;


--2..WAQTD NAMES OF ALL THE EMPLOYEES.

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES;


--3.WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES.

SELECT FIRST_NAME,LAST_NAME ,SALARY FROM EMPLOYEES;


--4.WAQTD NAME AND COMMISSION GIVEN TO ALL THE EMPLOYEES.

DESC EMPLOYEES;

SELECT (FIRST_NAME || LAST_NAME) NAME,COMMISSION_PCT  COMMISSION FROM EMPLOYEES;

--5.WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL THE EMPLOYEES

SELECT employee_id,department_id DEPARTMENT_NUMBER FROM EMPLOYEES;


-- 6.WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES .

SELECT * FROM EMPLOYEES;
-- to rename the column
SELECT (FIRST_NAME || LAST_NAME) ENAME,HIRE_DATE HIREDATE FROM EMPLOYEES;

ALTER TABLE employees RENAME COLUMN job_id TO designation;
commit;

--7.WAQTD NAME AND DESIGNATION OF ALL THE EMPLPOYEES 

SELECT (FIRST_NAME || LAST_NAME) NAME,designation FROM employees;



--.WAQTD NAME , JOB AND SALARY GIVEN ALL THE EMPLOYEES. 

SELECT (FIRST_NAME || LAST_NAME) NAME,SALARY,designation JOB FROM employees;


--9.WAQTD DNAMES PRESENT IN DEPARTMENT TABLE


SELECT * FROM departments;

SELECT DEPARTMENT_NAME DNAMES  FROM departments;


-- 10.WAQTD DNAME AND LOCATION PRESENT IN DEPT TABLE.
SELECT * FROM departments;

SELECT DEPARTMENT_NAME DNAMES,LOCATION_ID FROM departments;

