--1.WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY 

SELECT e.ename name,e.sal salary FROM EMP e ;

--2.WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE WITH THEIR HALF TERM SALARY.

SELECT e.ename,e.job,e.sal/2 TermSalary  FROM EMP e;


--3.WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH AN ANNUALBONUS OF 2000.

SELECT e.*, e.sal + 2000 increased_salary
FROM emp e;

--4.WAQTD NAME SALARY AND SALARY WITH A HIKE OF 10%

SELECT e.ename,e.sal,e.sal+sal*0.10 Hikesalary  FROM EMP e;


--5.WAQTD NAME AND SALARY WITH DEDUCTION OF 25%.

SELECT e.ename,e.sal-sal*0.25 RevisedSal FROM EMP e;

--6..WAQTD NAME AND SALARY WITH  MONTHLY HIKE OF 50

SELECT e.ename,e.sal,e.sal+50 monthlyHike  FROM EMP e;

--7.WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION OF 10%
SELECT e.ename,e.sal,e.sal-sal*0.10 total_salary FROM EMP e;

--8.WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE (SAL+COMM)

SELECT e.sal+comm Total_Sal FROM EMP e;


--9.WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY

SELECT e.*,e.sal*12 annual_Salary FROM EMP e ;


--10.WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALTY IN SALARY

SELECT * FROM EMP;

SELECT e.ename,e.job,e.sal+100 penality FROM EMP e;

