ASSIGNMENT ON EXPRESSION & ALIAS

SELECT * FROM EMPLOYEES;

// 1.WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY.

SELECT FIRST_NAME ||' '|| LAST_NAME NAME,SALARY  FROM EMPLOYEES;

// 2.WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE WITH THEIR HALF TERM SALARY.

SELECT FIRST_NAME ||' '|| LAST_NAME NAME,DESIGNATION JOB ,SALARY/2 HALF_TERM_SAL FROM EMPLOYEES;
